version: '3'
services:
  ##############################
  # WASM/WASI app + Dapr sidecar
  ##############################
  grayscale-app:
    image: rustwasm/image-http-grayscale
    build:
      context: image-grayscale
      dockerfile: image-grayscale/Dockerfile
    platform: wasi/wasm
    runtime: io.containerd.wasmedge.v1
    ports:
      - "50001:8080"
    depends_on:
      - postgres
      - redis
      - kafka
      - placement
    networks:
      - dapr
  grayscale-app-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "grayscale-app",
    "-app-port", "8080",
    "-placement-host-address", "placement:50006"]
    depends_on:
      - grayscale-app
    network_mode: "service:grayscale-app"
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - dapr
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - dapr
  ###########################
  # Postgres DB
  ###########################
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  ###########################
  # Kafka message bus
  ###########################
  kafka:
    image: docker.redpanda.com/vectorized/redpanda:latest
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 9644:9644
      - 29092:29092
    networks:
      - dapr
networks:
    dapr: